### ISSUE TITLE
Device not detected

### ISSUE THREAD

**Issue by SebastienBenazet** [nvdweem/PCPanel#1]
Hi ! 

I was looking for a solution to fix the shutdown issue with the official software and stumbled upon this thred : https://www.reddit.com/r/PCPanel/comments/uyhh4f/any_way_to_fix_the_sndctrlexe_power_down_issue/

I tried v1.3 and 1.4-SNAPSHOT but i got a "NO DEVICES CONNECTED" on both versions, even after a clean install and reboot.

Please find attached the [logging.log](https://github.com/nvdweem/PCPanel/files/8928640/logging.log) file if that can help you solve the issue 

I'd really love to give your version a try, as the official one kinda sucks.

Cheers!

**Comment by nvdweem** [comment]
Hey, 

I see you have a PCPanel mini, I've been developing and testing this on my PCPanel pro so there were bound to be some issues for other devices :).

I think I was able to reproduce the issue from your logfile and I just pushed a change that should fix it. Chances are that it will just trigger the next issue but I'm hoping it will actually work now. If it doesn't you can send the logfile with the new errors again ;).
The new 1.4-SNAPSHOT release should contain the fix.

By the way, this version is _very_ close to the original version so if there are any other issues you have with the original I might be able to look into those as well.
