### ISSUE TITLE
Unable to control volume - Linux

### ISSUE THREAD

**Issue by 5a3ee** [nvdweem/PCPanel#19]
I am unable to use the device to control audio. 

# Details
The setup instructions have been followed for Linux. 
The app launches graphically if I use sudo, but only stays in the panel otherwise. I am unable to control the volume or see any audio devices when launching it with sudo. 

Despite copying the profile I created with the root user to my own user, the device's LEDs remain off when launched without sudo. 

I believe the issue stems from the parsing of the pactl output.

Logs are included below:
[output.log](https://github.com/nvdweem/PCPanel/files/10013029/output.log)

**Comment by kastoreion** [comment]
Can you provide more information about your install, in order for me to reproduce the issue?

**Comment by nvdweem** [comment]
From what I can tell in the log, you are not using the most recent snapshot. This specific issue should have been fixed in the most recent snapshot already.

**Comment by 5a3ee** [comment]
Indeed, the latest version fixed the issue, apologies.

**Comment by nvdweem** [comment]
No problem, the snapshots aren't easily identifyable and don't have update-checks so ensuring that you are on the latest is currently as hard as I can possibly imagine it :).
