### ISSUE TITLE
Empty JavaEmbeddedFrame

### ISSUE THREAD

**Issue by kastoreion** [nvdweem/PCPanel#20]
**Description:**

When PCPanel opens up an additional empty window titled "JavaEmbeddedFrame" appears. The icon in the tray is working correctly but the icon is "floating" under the taskbar.

**Configuration:**

OS: Debian GNU/Linux bookworm/sid x86_64
Kernel: Kernel: 6.0.0-4-amd64
DE: GNOME 43.1
Windowing System: X11
PCPanel: [v1.6-SNAPSHOT Pre-Release](https://github.com/nvdweem/PCPanel/releases/tag/latest-windows) (pcpanel_1.6-SNAPSHOT-1_amd64.deb)

**Steps to reproduce:**

Execute: /opt/pcpanel/bin/PCPanel

**Additional context:**

![Screenshot from 2022-11-15 15-43-18](https://user-images.githubusercontent.com/36232657/201938222-48a7ff1d-4f06-43b9-aa94-46fa1de6ee63.png)

![Screenshot from 2022-11-15 15-43-39](https://user-images.githubusercontent.com/36232657/201938274-800f6f08-fe7b-4d4a-97a5-22368cc0fa3b.png)

A similar issue with an other application can be found here: https://github.com/cryptomator/cryptomator/issues/1078

**Comment by kastoreion** [comment]
Update, if you disable tray icons completely the Empty JavaEmbeddedFrame does not appear at all.

**Comment by nvdweem** [comment]
Good to know. With 'disable tray icons', do you mean essentially disabling TrayService.init? If so, I can probably make that bean conditional on a command line parameter so that it can easily be disabled.

What is the default behavior for services that are supposed to run constantly on Linux where there is no tray? How would you open the UI? Currently that could be done by running the executable again, but I'm not sure what other options would be.

**Comment by nvdweem** [comment]
I added a command line toggle to disable the tray. This can be done by running the application with a `-Ddisable.tray` argument. This can also be done using an environment variable `DISABLE_TRAY=true`.
When the tray is disabled, the close button on the main window will be hidden and closing the window anyway will shutdown the application.

**Comment by kastoreion** [comment]
I apologize for the late reply.

Installed latest commit [db2c58b](https://github.com/nvdweem/PCPanel/commit/db2c58b213bf09d609b2343e152f54ac00adfb47) and added `export DISABLE_TRAY=true` to `~/.profile`. Can confirm it works. Also, used this extension https://github.com/danigm/hide-minimized to hide the minimized application and now it only shows in the dock as active.

![image](https://user-images.githubusercontent.com/36232657/202591876-31421300-1450-4a40-8ea0-b919b2e4807f.png)

Can the close button still be enabled and just run in the background no tray while tray extension is enabled? The app is only opened from time to time to edit profile.

**Comment by nvdweem** [comment]
Yeah, I wasn't entirely sure about not being able to close the application :)

I've reverted the not being able to hide the main window and changed the description in linux.md to explain that the main window can be shown by trying to start the application again (the second instance should show the main window from the first one and then close itself).

**Comment by kastoreion** [comment]
Just reinstalled latest commit [b10f4fc](https://github.com/nvdweem/PCPanel/commit/b10f4fca5a0f4a45eb4a887e5ab6a45d08434562). Can confirm it works. Thank you very much!
