### ISSUE TITLE
Support for multiple streams for single process

### ISSUE THREAD

**Issue by CyberPenguin** [nvdweem/PCPanel#21]
Tested on Fedora 37

When controlling audio for a process, the slider or knob does not control all related streams if there is multiple.

An example of this would be if you had multiple tabs open in FireFox playing audio.

Seeing this feature implemented would be appreciated.

**Comment by nvdweem** [comment]
This should be fixed in v1.6-SNAPSHOT 110 and higher.

**Comment by CyberPenguin** [comment]
Thanks so much tested with multiple Firefox streams and its working like a dream.

This is a bit cheeky but I use an application called Mumble for talking with friends and for some reason the panel doesn't seem to be able to control it. This was what actually highlighted the multi stream support requirement originally for me. I don't suppose you could have a look at why its not working?

I know this is probably a separate issue now as multi stream support is working.

**Comment by nvdweem** [comment]
It seems that Mumble doesn't register with a PID or Executable with PulseAudio. The sessions were grouped by PID which meant that the Mumble session would be filtered out.
I made a change which should allow sessions that don't have a PID but do have a title to be controlled. This seems to help.

I haven't actually tested any audio from Mumble but the volume control UI shows that the volume gets changed now.
The fix should be in the 101 build which should be done building in a few minutes.

**Comment by CyberPenguin** [comment]
Tested and working, you are a hero thank you so much.
