### ISSUE TITLE
Focus Volume affecting input

### ISSUE THREAD

**Issue by DrowningWhale** [nvdweem/PCPanel#24]
**Describe the bug:**

Using focus volume changed the microphone input volume on Discord

**Steps to reproduce:**

Set dial/slider to Focus Volume, focus Discord, input volume changes

**Expected behavior:**

I expected only the output volume to change. I use the slider to change the volume of whatever game is focused.

**Additional context:**

Windows 11, latest snapshot

**Comment by nvdweem** [comment]
I just pushed a change that should fix this. Is should be part of the 1.6-SNAPSHOT build 113.

**Comment by DrowningWhale** [comment]
Confirmed fixed, ty!
