### ISSUE TITLE
Mute override follow Voicemeeter source/sink

### ISSUE THREAD

**Issue by Spenser715** [nvdweem/PCPanel#29]
I love the added feature to be able to have a mute override change the color of the RGB to show that that is muted. I see it currently only allows following devices or there is the option to use what the knob controls. The problem is that this doesn't seem to work for Voicemeeter controls.

**Comment by nvdweem** [comment]
This should be included in Snapshot build 120. It required polling so the mute color can lag behind by a second but I'm expecting that not to be a big issue..

**Comment by Spenser715** [comment]
Wonderful thank you.
