### ISSUE TITLE
v1.6-SNAPSHOT (118) crashes when opening applications

### ISSUE THREAD

**Issue by jaharkema** [nvdweem/PCPanel#31]
**Describe the bug:**

The app crashed when I opened another app next to it. This happened with Firefox, Discord and Tidal. I didn't test if it is relevant, but I have set up all three of these apps/processes to be controlled by the PCPanel.

**Steps to reproduce:**

- Start PCPanel. Keep the window open/visible (so not minimized or closed to tray)
- Start either Firefox, Discord or Tidal
- The PCPanel window disappears and a Windows error message shows up:

> PCPanel.exe has stopped working
> A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

**Expected behavior:**

The PCPanel app does not crash :-)

**Additional context:**

Windows 10 Pro, 10.0.19045 build 19045
PCPanel Controller 1.6-SNAPSHOT (118)
I have the PCPanel Mini.

Relevant crash dumps from `%localappdata%\CrashDumps`: [CrashDumps.zip](https://github.com/nvdweem/PCPanel/files/10368598/CrashDumps.zip)

Edit to add:
Tested with Firefox: If Firefox is open at the time I start PCPanel, opening new windows does not cause PCPanel to crash.
Tested with Discord: If Discord is open at the time I start PCPanel, I can freely quit and re-start Discord without crashes.

The first time PCPanel crashes after a reboot or reinstall (I did both, so I'm not sure which one influences the outcome), PCPanel just closes. Windows does not give an error and no new file appears in the `CrashDumps` folder.

Log file from `C:\Users\<user>\.pcpanel\logs`: 
[logging.log](https://github.com/nvdweem/PCPanel/files/10368620/logging.log)

**Comment by nvdweem** [comment]
The crashdumps seem to indicate that the JVM is crashing without any interaction from the code from the application (which would be strange).
The current snapshot (125) has a fix which the dump didn't indicate that occurred, but also uses a newer Java version. Could you try and see if that version does start?

**Comment by jaharkema** [comment]
Snapshot 125 gives another error for me: "Failed to launch JVM". This could very well be an issue on my side though. 
It's been ages (i.e. about 20 years) since I did any Java development, so I'm not sure where to look for logs or how to fix this error.

Some info, which may or may not be relevant info:

I have a Windows System variable `JAVA_HOME: D:\Program Files\Java\jdk-17.0.5`
Some output from CMD:
```
>java -version
java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)

>where java
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe 
```

Does this help you in any way, or is my entire Java installation just f'ed? 😄

**Comment by nvdweem** [comment]
The logs should be written to `%userprofile%/.pcpanel\logs`, but if there is a "Failed to launch JVM" then it could be the case that the installer is wrong and that it won't actually log anything.
I had another crash myself with Snapshot 125 indicating that the issue I attempted to fix isn't fixed so I'll have to try another fix later again.

**Comment by jaharkema** [comment]
Logs from `%userprofile%\.pcpanel\logs` are attached. From what I understand by skimming over them, I'm now encountering the same issue as #26 which is somewhat comforting for me 😄 
[logging.log](https://github.com/nvdweem/PCPanel/files/10376012/logging.log)

**Comment by nvdweem** [comment]
Build 127 should fix that specific issue :)

**Comment by jaharkema** [comment]
Build 127 works as I'd expect it to (so far). The PCPanel app opens and after I started it, I started both Discord and Tidal which work fine. Volume control also works as expected, with at least Tidal and Firefox. I assume other apps work as well.

As far as I'm concerned, build 127 fixes the issue I ran into, so I'll close this issue.

Thanks for your support and quick fixes!
