### ISSUE TITLE
Add option to start software on Windows Startup

### ISSUE THREAD

**Issue by pkim168** [nvdweem/PCPanel#32]
Request: Add an option somewhere that when checked will start the software when Windows starts.

Although I have PCPanel set to start with Windows through Task manager, sometimes it doesn't work and I have to start it manually.

**Comment by nvdweem** [comment]
Are you using the latest 1.6 snapshot? A few errors were fixed recently that could cause the software to crash (for me that happened mostly on startup).

Currently the installer will always add the software to the startup applications. So if it doesn't start up there is either something wrong with Windows for it not to attempt the startup, or the software crashes before you see it. You should be able to see in the log if the software attempted to start up.
