### ISSUE TITLE
Spawns a little window

### ISSUE THREAD

**Issue by LGXerxes** [nvdweem/PCPanel#33]
**Describe the bug:**
When launching PCpanel manually or with an autolaunch on Linux (pop!os 20.4 kernel 6).
It spaws a little window
![image](https://user-images.githubusercontent.com/68999840/213799374-40074214-3d39-4b92-ba20-e0b4a8693f1a.png)

**Steps to reproduce:**
Install Pop!os
install PCpanel as the installations.
launch with sudo PCPanel
add PCPanel to startup applications
Restart PC
Login and see little window in the corner.

[logging.log](https://github.com/nvdweem/PCPanel/files/10470033/logging.log)

**Comment by nvdweem** [comment]
That't the tray icon as identified by #20, it's possible to disable it via by adding `-Ddisable.tray` as a command line parameter, or `DISABLE_TRAY=true` as environment variable.

**Comment by LGXerxes** [comment]
![image](https://user-images.githubusercontent.com/68999840/213910704-dc4c9cd1-12c4-4831-bd7c-8d72ee6ccb23.png)

With -Disable.tray it still shows the tray icon

**Comment by nvdweem** [comment]
It looks like my info was incomplete.
1. You are using version 1.5, the fix is in the 1.6 snapshot
2. The -Ddisable.tray (it's also -D and then disable.tray, but in your screenshot you did it correctly) option will only work if you run the jar, when you run the 'executable' like you are it's not possible to pass the argument

So, in your case you would have to update to the latest snapshot and do
```
export DISABLE_TRAY=true
/opt/pcpanel/bin/PCPanel
```

**Comment by LGXerxes** [comment]
1.6 snapshot is not dispalying the application, only the tray icon in the corner
[pcpaneldebug.txt](https://github.com/nvdweem/PCPanel/files/10474464/pcpaneldebug.txt)

Adding export DISABLE_TRAY=true to ~/.profile , does not hide the icon on 1.6 snapshot.
Probably due to the error of launching it ^

Will try with the .jar now

**Comment by LGXerxes** [comment]
[pcpaneldebugjava.txt](https://github.com/nvdweem/PCPanel/files/10474496/pcpaneldebugjava.txt)
basically the same error.
Seems like the commit of voicemeeter might have changed something?

**Comment by nvdweem** [comment]
The VoiceMeeter error should be fixed.

**Comment by LGXerxes** [comment]
Latest snapshot release fixed everything :)
