### ISSUE TITLE
Mute override based on Voicemeter output selection

### ISSUE THREAD

**Issue by cr45hmurphy** [nvdweem/PCPanel#34]
I utilize the PCPanel Mini to control several channels on Voicemeter Potato and Banana (different computers for each). I know that the mute override currently works if you set a button press to mute a Voicemeter channel. However, I would like for it also to work if it's set to an output button.

For example, I utilize one input channel (my mic) and two output channels: Discord and System. On my other computer, I use one input (my mic) and three outputs: Teams, Zoom, and System. 

This allows me to talk on different channels simultaneously while having the freedom of muting between the tracks. So, I could be on a Teams call, and a Zoom call simultaneously and still can mute one call while talking on the other. I do this by setting up macro buttons (Voicemeter Macro Buttons) that toggle the sending of the mic to those channels. So, they toggle the B1/B2/B3 buttons on the input channel. 

I am not going to presume to know how difficult or easy it is to add features. However, whatever is being done to "look" for the Mute option on the button push could also be extended to the B1/B2/B3...etc. buttons, since they are technically the "input send" buttons within Voicemeter.

Photo attached, in case that helps:

![image](https://user-images.githubusercontent.com/4840152/213841044-2a7d92b7-c9c5-42e2-abe3-d30f83b3ec6e.png)

**Comment by nvdweem** [comment]
For audio devices there is the option to not 'Follow the dial action' but to choose a device specifically.

Would it be sufficient for your usecase if the dropdown would list the VoiceMeeter sliders so you can just choose one to follow, or would it require following the B-button states for mutestate?

**Comment by cr45hmurphy** [comment]
That's a good question! If I'm following your question correctly, you're saying that the drop-down would be able to follow an actual slide within Voicemeter, and then the dial could be set to turning on a button on that slider (A1 thru Mute) and this would generate the mute override color? In other words, the button press could be agnostic to the actual "Mute" selection on the Voicemeter slider, and would simply look to see if the button action was pressed?

**Comment by nvdweem** [comment]
I'm not super familiar with VoiceMeeter, but I think your rephrase isn't exactly what I meant :).

Sliders don't have a mute state, they can have a value between min and max, but min isn't muted. The muted toggle means muted. Also, the mute state on the PCPanel isn't bound to button presses, but the mute state of something else. Currently the VoiceMeeter option is the mute state of an input/output (the mute buttons on your screenshot).
So it's just: If 'Input 1, Mute' is enabled, the color is 'some color'".

My question is about adding options in the dropdown like 'Input 1, A1', 'Input 1, A2', 'Input 2 B1' etc and have the mute color of the pcpanel follow the toggled state of one of those.
So essentially, "If 'Input 1, A1' is enabled, dial color is 'some color'".

Even if that A1 toggle is the enabled state, you could put the default color to the color you want to have as muted and use the 'mute state' option as an 'unmute state'.

**Comment by cr45hmurphy** [comment]
Ahhh! Beautiful! Yes, I think that would work wonderfully!

Thank you for the clarification. I think that you have a general idea of what I'm looking for, so I trust your intuition and direction on how to implement.

**Comment by nvdweem** [comment]
The next build should show a list of all VoiceMeeter options in the mute-state tab of the lighting dialog.
Currently, that's the Inputs with multiple button states and the outputs with the mute-state. The top right states (next to the tape) aren't currently supported, but I don't think you were pointing to those.

The options should be limited to the VoiceMeeter application that's currently running  (VoiceMeeter should show A1/B1, Banana shows more and with Potato the list of options is quite huge).

**Comment by cr45hmurphy** [comment]
@nvdweem Latest release fixes this 100%! Works without issue, as far as I can tell. Will even dynamically adjust whether the mute state is triggered via the knob click, or software button. Thank you so much for this fix!
