### ISSUE TITLE
Volume not being changed

### ISSUE THREAD

**Issue by LGXerxes** [nvdweem/PCPanel#35]
**Describe the bug:**

Focus Volume not working on Linux
And Specific process not working or unsure which name/id to pick.

Pactl list sources output:
[pactllistsources.txt](https://github.com/nvdweem/PCPanel/files/10474204/pactllistsources.txt)

Output is on Source #700
2.1 Spearks

--
Tested it with dial - 1 on process "Nightly"
dial -2 on Focus Volume

pactl subscribe
![image](https://user-images.githubusercontent.com/68999840/213911854-6ef8cc07-70ac-446d-9da4-fdb7b539ba69.png)

start music on firefox nightly on music.youtube.com
See the 'new' event for #842

**Comment by nvdweem** [comment]
Apparently I was wrong about the `pactl list sources`, that's for the input devices. The audiosessions are from `pactl list sink-inputs`. Would it be possible to include the output from that command as well?

The `list sources` output seems to parse correctly, so I'm not really expecting any issues with the `sink-sources` list. If it parses without issue I probably need to add some additional logging to be able to help.

**Comment by LGXerxes** [comment]
[pactllistsink-inputs.txt](https://github.com/nvdweem/PCPanel/files/10474691/pactllistsink-inputs.txt)
This is the output of a
pactl list sink-inputs

**Comment by nvdweem** [comment]
That output seems to be parsed fine as well. I did try the 1.5 version on my PopOS VM and it seems that I have the same issues as you described, no options in the process picker and volume changing not working. 
Chances are that updating to 1.6 will also fix this issue.

**Comment by LGXerxes** [comment]
The latest snapshot seems to have fixed everything.

.deb works great.
Application finder and focus volume are working :D

`export DISABLE_TRAY=true`
Also hides the icon from #33 

Thankyou immensely!
