### ISSUE TITLE
Custom overlay images

### ISSUE THREAD

**Issue by Spenser715** [nvdweem/PCPanel#36]
I love the system overlay that shows the volume meter on screen. It would be great to be able to customize the image in some way. I have all my knobs set to Voicemeeter controls so they all just show the Voicemeeter icon. And all my sliders are set to physical devices so they just show the speaker icon.

**Comment by nvdweem** [comment]
For knobs/sliders there is an 'Overlay icon' option in the settings. You should be able to pick an image there which will be used. It's not used for buttons, but it should be possible to add another option for that.

**Comment by Spenser715** [comment]
Thank you. I must have been on an old version of the software that didn't have it. I updated and now I can change them.
