### ISSUE TITLE
Double button click

### ISSUE THREAD

**Issue by Rosux** [nvdweem/PCPanel#38]
I don't have the java skills to add a double click feature myself but it would be really nice to have a double click with some timeout so you can choose how fast to click. Could have the same functionalities as the normal button click.

**Comment by nvdweem** [comment]
I'm planning to make the 1.6 snapshot the 1.6 release soon. I'll look into double clicking after that.

Usually I don't like double click options myself due to the main click having to be delayed. But it should be possible to make single clicks execute instantly if there isn't a double click and allow waiting or executing both actions etc.

**Comment by nvdweem** [comment]
The feature should be available in the 1.7 snapshot.
There is now a 'Dbl click' tab on the macro form which has the same options that the Button panel has which will be executed on double click. 

The main settings panel has options to configure the double click:
- Double click interval (ms): Within how many ms should the second click occur to see it as a double click
- Don't click until it's sure that it won't be a double click: Checked to wait for the interval before triggering a double click, when unchecked you will trigger both the regular click and the double click when double clicking (I'm open for suggestions for a better label :))

If a button does not have a double click action, the click action will be executed instantly even with the checkbox checked. The double click will not be delayed.

**Comment by Rosux** [comment]
works pretty nice. "Trigger both functionalities at double click." could make it more clear (have to invert the checkbox though). also could make it that if the dbl click has no functionality it just instantly does the single click (if that's not being worked on, to remove the delay when no double click is set.

**Comment by nvdweem** [comment]
"Trigger both functionalities at double click." is clear in what it does, but hides the downside of delaying the single-click, but that could be the tooltip.

"also could make it that if the dbl click has no functionality it just instantly does the single click" that's already implemented and what I meant is the behavior with my last line :). It's also the reason why the button pages now have a 'No action' option.
