### ISSUE TITLE
AZERTY Layer bug when PCPanel.exe is running

### ISSUE THREAD

**Issue by SebastienBenazet** [nvdweem/PCPanel#4]
I'm having issues with the keyboard layer when PCPanel.exe is running.
I'm on _French FR (AZERTY)_ default Windows 10 layer

Somes keys won't work such as : ^ ~ `
![image](https://user-images.githubusercontent.com/6958576/174960841-ef986258-30bc-40f0-b548-b6cc4fbcfed2.png)

If I kill the PCPanel.exe process, the keyboard work perfectly.

Could you take a look at it please ?

**Comment by nvdweem** [comment]
It seems that I had the wrong groupid for the jnativehook dependency (allows for shortcuts to change profiles) which meant that it was using an older version that seems to have this issue.

I think it should work now but I'm not 100% sure how French keyboards are supposed to work (are the numbers really not the numbers without pressing shift?). The ^ is now a dead key again so if I press e after it it becomes ê which is what I think you meant that was wrong.

**Comment by SebastienBenazet** [comment]
Yes on French keyboard you are supposed to press shift to type number.

Your new version works 100% ! Thanks again !
