### ISSUE TITLE
Voicemeeter set to 1 when slider set to -60

### ISSUE THREAD

**Issue by arl8** [nvdweem/PCPanel#41]
**Describe the bug:**

When the slider is set to -60 through voicemeeter and Windows 10 is restarted, voicemeeter sets slider to 1 when slider is still at -60 state. 

**Steps to reproduce:**

Set slider all the way down on PcPanel Pro
Voicemeeter corresponds to -60
Restart windows
Open voicemeeter 
Slider sets itself to 1

**Expected behavior:**

Slider use to correspond to last state it was in when voicemeeter restarts. Or if slider is changed when computer is off, voice meter should set volume state to slider position 

**Additional context:**

Add context for the issue, Windows/Linux, which version of the application and what device do you use

**Comment by nvdweem** [comment]
1.7 build 142 should set the VoiceMeeter (and OBS) volumes when the PCPanel software connects to those. I think that is what you are asking about, right?
