### ISSUE TITLE
No button options on v1.7-SNAPSHOT

### ISSUE THREAD

**Issue by ironicsayte** [nvdweem/PCPanel#43]
I'm unsure if I am doing something wrong, but whenever I attempt to use the 1.7 release there are no options to configure the knob buttons, only the knob sliders themselves. See attached screenshot. Any advice is appreciated!

![PCPANEL V1 7](https://user-images.githubusercontent.com/76626745/226136265-ecc9b8dc-149d-40fe-bc28-fa86dfef092b.png)

**Comment by nvdweem** [comment]
Looks like you are doing nothing wrong, I did something wrong :).
Should be fixed in Build 146.
