### ISSUE TITLE
Arch linux using java version - no output devices visible

### ISSUE THREAD

**Issue by sandivuk** [nvdweem/PCPanel#44]
Hello,

I am attempting to run this tool using the java version as I am on Manjaro linux (arch-based). I can run the app successfully and the knobs and buttons appear to function in the GUI, reacting to turns and button pushes and lighting adjustments. However, I can't get the java version to do anything else. 

1. For example, the application finder does not seem to do anything and there is no effect if I manually type in a application name
2. There are no output devices listed anywhere, the drop-down selectors for output devices show nothing
3. Setting dial options to All Output Devices likewise has no effect on any system volume

I have Pipewire installed and running on this system. At the moment the only thing that functions is turning the knobs and seeing the result in the GUI, as well as controlling the lighting. 

There seems to be at least one user here who got it working via Java on Arch-based linux so I'm curious what if anything I did wrong

Thanks!

**Comment by nvdweem** [comment]
I'm not sure if I updated the documentation when I checked the pipewire compatibility. The linux.md still mentions a dependency on `pulseaudio-utils` but I'm not entirely sure if PipeWire already includes the required command.

Is the `pactl` command available on your system? If it isn't then controlling the volume won't do much. Even though it's a PulseAudio command, it should be able to control PipeWire as well.

**Comment by sandivuk** [comment]
Thanks for the reply. The pactl command is available on my system and runs. I should note that I also tried this on a fresh install with only pulseaudio rather than pipewire and I had the same result. Its like the Java version exists in a bubble where it can only talk to the physical pcpanel device and nothing else. No applications are shown, no devices, nothing

**Comment by nvdweem** [comment]
I just checked with a clean install where I used Dutch as OS language and it seems that `pactl` uses the system language in its output.  `pactl list sources` shows Dutch labels and that's not expected by the software.

Could you try and see if that's also the case for you?

If it is, could you try and run `export LC_ALL=C` before running the application, for instance:
```
export LC_ALL=C
java -jar pcpanel-1.6.jar
```

**Comment by sandivuk** [comment]
Hello,

My apologies for the delayed response. I want to quickly say that my pactl command showed just english sources. 

I've had some things going on and rebuilt my Linux OS with arch + wayland for now. I'll play with this later and see if it works. At least one other user here reports this tool working under arch and wayland
