### ISSUE TITLE
Support for Write Only Voicemeeter Parameters & Voicemeeter Parameter Toggle

### ISSUE THREAD

**Issue by AaronJWhite** [nvdweem/PCPanel#45]
**Feature Request 1:  Support for Write Only Voicemeeter Parameters**

I am trying to use the VM parameter (Strip\[i\].device.wdm) to set the device of one my Voicemeeter hardware inputs.  It seems like PCPanel cannot use VM parameters where you have to write a value. Please add the ability to use VM parameters like Strip\[i\].device.wdm where you would set a text value.What I have tried with control mode as enable is:  `Strip[4].device.wdm = "RØDE NT-USB Mini"`This is from the VM documentation :**Strip Audio Devices (physical strip only)**

|Parameter Name|Value Range|Remark|Version|
|:-|:-|:-|:-|
|Strip\[i\].device.name|String|Read only|1|
|Strip\[i\].device.sr|samplerate|Read only|1|
|Strip\[i\].device.wdm|Device Name|Write only|1|
|Strip\[i\].device.ks|Device Name|Write only|1|
|Strip\[i\].device.mme|Device Name|Write only|1|
|Strip\[i\].device.asio|Device Name|Write only|1|

**Feature Request 2:  Voicemeter Parameter Toggle**

I would like the ability to click a Knob and have it toggle or cycle through multiple Voicemeeter Parameters. So combined with feature request 1 above I could create a button click that toggles between the following parameters to change the device of a VM hardware input. Obviously a feature like this could have more uses.Param 1:`Strip[4].device.wdm = "RØDE NT-USB Mini"`Param 2: `Strip[4].device.wdm = "Headset Microphone (example)"`

I imagine the interface for something like this could look like the Voicemeeter advanced tab in the OEM software, but it would have a plus icon or something to add extra parameters.

\---------------

Note: I can split these two feature requests out. I originally requested them on the pcpanel reddit last year.

**Comment by nvdweem** [comment]
It should be fine to have both features in a single issue.

In the 1.7 snapshot version I've been adding the option to have more than one action for the triggers. Currently they will all trigger, but I was already planning to add an option that would allow rotating the actions. That way, any singel action would be able to become a toggle instead of adding toggle like options for all actions where it would make sense.

I'm currently a bit busy with other things but I'll try to make some time to implement these suggestions soon.

**Comment by nvdweem** [comment]
I have attempted to implement both features. From what I could tell, the issue with the 'write only' parameters isn't so much that those weren't supported as it was that there wasn't an option to send string values, only booleans.
The advanced tab for Voicemeeter should now include String as an option in the dropdown.

For the second feature there is now the 'Run all at once' and 'In sequence' option next to the 'Add action' button (when there is more than 1 action).
To be able to control the sequence it's now also possible to move commands up and down, and copy them.

**Comment by AaronJWhite** [comment]
Awesome. About when do you think the next release with these changes come out?

**Comment by nvdweem** [comment]
There isn't a release date for the next version yet, but snapshot builds are published a few minutes after each change. If you go to the releases page you'll find the [snapshot version](https://github.com/nvdweem/PCPanel/releases/tag/latest-windows) at the top of the page. The current snapshot (151) includes these changes.

**Comment by AaronJWhite** [comment]
> There isn't a release date for the next version yet, but snapshot builds are published a few minutes after each change. If you go to the releases page you'll find the [snapshot version](https://github.com/nvdweem/PCPanel/releases/tag/latest-windows) at the top of the page. The current snapshot (151) includes these changes.
Got it. Thank you!
