### ISSUE TITLE
Unable to configure knobs

### ISSUE THREAD

**Issue by mehistaken** [nvdweem/PCPanel#46]
**Describe the bug:**

Since updating to 1.7-SNAPSHOT (148) I can no longer configure knob behavior, clicking on them in the UI has no effect. They still perform actions as previously configured but I can no longer be change.
Sliders work as expected

**Steps to reproduce:**

- Open PCPanel Controller via system tray
- Click on any knob
- Nothing happens

**Expected behavior:**

Configuration of individual knob should popup

**Additional context:**

Win11 Home 64-bit (build 22621)

**Comment by nvdweem** [comment]
Should be fixed in build 150.

**Comment by mehistaken** [comment]
Confirm fixed in 151
