### ISSUE TITLE
Use this software with a OpenHardware

### ISSUE THREAD

**Issue by odacristo** [nvdweem/PCPanel#51]
Hello!

Have a way, to use a opensource hardware (arduino?) to run on this software?
If yes, this project exist at this time?

Thanks!

**Comment by nvdweem** [comment]
You can copy the source, so there is a way if you can develop software (Java), but currently the software doesn't support anything other than PCPanel hardware. The original author of the software also indicated that they wouldn't like their software to be used for other hardware.

Even though most of the source in this repo has been rewritten, it was derived from the original source code which I think means that the original authors still own it. It's currently tolerated by the PCPanel people, but I wouldn't expect that to last if it starts competing with their product.

**Comment by odacristo** [comment]
Thanks a lot for the repply!
