### ISSUE TITLE
End Task function not working

### ISSUE THREAD

**Issue by BigbyBear** [nvdweem/PCPanel#57]
I set one of the dial buttons to end focused task and it does not close the focused program (attempted on multiple programs), it will close a specified program though.
I use windows and its a problem with both the 1.7-snapshot (152) and the main 1.6 version as well

**Comment by nvdweem** [comment]
This should be fixed in the next 1.7-snapshot build.
The implementation did a `taskkill /im [full application path] /f` but should have done (and now does) a `taskkill /im [executable] /f`. There might be another improvement if it killed based on PID, but for now I left it at executable.
