### ISSUE TITLE
Support for control mode -60 to 12 in Voicemeeter advanced settings

### ISSUE THREAD

**Issue by ethw** [nvdweem/PCPanel#58]
Voicemeeter provides gain faders from -60db to 12db. It is currently not possible to control this full range through PCPanel pro and this software as far as I can tell.

If you use the default control mode, -Inf to 12, then voicemeeter gets stuck at -60 when the pc panel fader is all the way at the bottom. Voicemeeter is interpreting that as [-1000db or something like that](https://www.reddit.com/r/PCPanel/comments/x0i1a9/voicemeeter_volume_issue_with_pcpanel_pro/), resulting in voicemeeter being unreactive to fader changes until voicemeter is restarted.

If we had the option to control voicemeeter between -60 and 12db then the -1000db issue wouldn't occur and the full volume range of voicemeeter would be controllable via pc panel pro.

Thanks for considering.

**Comment by nvdweem** [comment]
I don't understand what you mean exactly. I don't use VoiceMeeter myself, so could you explain in a bit more detail what you are seeing and what you expect to see?

![java_MZv6eLp3mK](https://github.com/nvdweem/PCPanel/assets/830783/47fbba2e-b296-4a9c-8135-d7d932b2a8c6)
From what I can tell, the slider moves correctly between +12 and -inf. The only 'stange' behavior I'm noticing is that when restarting VoiceMeeter, changes made in the UI seem to be stored but changes from the PCPanel are not, but that isn't the issue you are seeing, right?

**Comment by ethw** [comment]
Sure, I'll explain more. Your screencap is definitely not my experience, here's what I'm getting.

![PCPanel_XaXIK9I0ir](https://github.com/nvdweem/PCPanel/assets/9457378/d44b1834-7bf9-4dff-8789-b84e82cc1e7a)

The voicemeeter slider gets stuck at the bottom. It won't move again until I restart voicemeeter. Even if I manually click in voicemeeter to move the slider the gain doesn't change.

I'm using voicemeeter potato, maybe it's a version difference. I see that you're on the basic version of voicemeeter in your screencap.

The reddit thread I linked in my original post had someone with the same issue who found that their voicemeeter xml file was set to something like -1000 for the affected voicemeeter strip. My guess is in that `-inf` is somehow setting the value too low on my voicemeeter version. Seems really weird that it's working on basic voicemeeter and not potato though. Could definitely be bad config on my part.

I guess a -60 to 12 mode might not be the answer if this is already working on basic voicemeeter. 

I'm on voicemeeter potato version 3.1.1.1. Thanks for looking into my issue!

**Comment by ethw** [comment]
![image](https://github.com/nvdweem/PCPanel/assets/9457378/89a87db6-56d8-4abf-bd2c-94655a428a12)

The [Voicemeeter potato](https://vb-audio.com/Voicemeeter/VoicemeeterPotato_UserManual.pdf) user manual says the value only goes between -60 and 12.

The [basic voicemeeter manual](https://vb-audio.com/Voicemeeter/Voicemeeter_UserManual.pdf) says the same thing though, so odd that it would only work on one of them.

**Comment by ethw** [comment]
I just tried out 1.7 and yep the -60 to 12 setting has resolved my issue. Thank you very much for the help.

![PCPanel_GGb7IbZls9](https://github.com/nvdweem/PCPanel/assets/9457378/db6efdef-7727-4120-a7ba-247d0cc60363)
