### ISSUE TITLE
Display Brightness regulation

### ISSUE THREAD

**Issue by der-grosse** [nvdweem/PCPanel#60]
I would really like to use the knobs to be able to control the brightness of my monitors, similar to the utility of [Twinkle Tray](https://github.com/xanderfrangos/twinkle-tray/tree/master). Having analog controls for that would be nice. I haven't done any research but I assume that there are probably packages for Java similar to the JS packages used in Twinkle Tray that could easily be used to implement the functionality.
This would be a more generic functionality than the just volume control, so I understand if you don't want to start adding such features.

**Comment by avenzi** [comment]
If you want a DIY solution, you can accomplish this by using the Open Sound Control interface. Many programming languages have packages that can accept signals using the OSC protocol and then you're free to do whatever you want with them. For example, you could probably do this with Python and [python-osc](https://pypi.org/project/python-osc/) + [monitorcontrol](https://pypi.org/project/monitorcontrol/).

**Comment by der-grosse** [comment]
Many thanks for the help! I'll try that.
