### ISSUE TITLE
Voicemeeter Gain Control locks to -60 After Reaching Lowest slider position

### ISSUE THREAD

**Issue by Benzeel** [nvdweem/PCPanel#65]
When using A knob or Slider to control the gain in a strip in Voicemeeter, once the gain reaches -60 (lowest slider position, leftmost knob position) it gets locked to that value, and breaks audio for that strip (no sound) even when moving the gain slider back up manually with your mouse in Voicemeeter. you have to shut down Voicemeeter and open it again to fix the audio in the affected strip(s).

if you move the knob/slider after manually setting the gain of the strip yourself in Voicemeeter, it will be reset back to -60 until you restart Voicemeeter. (not the audio engine) 
again, note that manually setting the gain slider in Voicemeeter wouldn't fix audio for that strip anyway, until you restart.

this happens regardless of the trim max setting being set lower than 100, and whether or not Logarithmic Scaling is checked or not in the PCPanel Controller Software
 
 
 this can be fixed by setting the trim minimum to 1 instead of 0 

**Steps to reproduce:**

set slider or knob in the pcpanel controller software to Voicemeeter control (Basic) with 'Input' selected, and 'Gain' selected with any Index.
open the Voicemeeter window, and turn knob all the way to the left / slider all the way down, then back up any amount on your PCPanel.
Slider is now stuck at -60 In Voicemeeter

**Expected behavior:**

Slider/Knob should change 'Gain' based on their position/rotation (slider/knob) without getting 'Gain' stuck at lowest value upon reaching it.

**Additional context:**

Pcpanel Controller v1.6, windows 11, Voicemeeter potato. tested with PCPanel Pro & Mini.

**Comment by nvdweem** [comment]
Have you tried the 1.7-snapshot version? I think this issue might have been fixed via #58.

**Comment by Benzeel** [comment]
yes, this fixed it, thank you!
