### ISSUE TITLE
Unable to handle device added - Pcpanel Pro

### ISSUE THREAD

**Issue by DeNo64** [nvdweem/PCPanel#66]
**Describe the bug:**

New install of the Java version on my Arch install. When launching it finds my device, but I get "Unable to handle device added" error. Pcpanel app opens and shows no device connected.

Java JRE and JDK installed, and JavaFX linked to run command as per linux.md

Tested on both 1.6 and 1.7-snapshot

And unplug/replugged pcpanel into pc

*log attached - [pcpanel-1.7-snap.log](https://github.com/user-attachments/files/17273960/pcpanel-1.7-snap.log)

**Steps to reproduce:**

Install JRE
Install JDK
Download JavaFX
Download Pcpanel.jar
Execute run command as per doc

**Expected behavior:**

Device should show in Pcpanel java app

**Additional context:**

Pcpanel Pro
Arch Linux
PulseAudio with utils - installed via Archinstall

Device works fine on Windows install

Happy to provide any additional info

**Comment by nvdweem** [comment]
I don't run Linux myself, so I'm not great at providing support for it. But if I'm not mistaken, this is what happens when the [Linux installation](https://github.com/nvdweem/PCPanel/blob/main/linux.md) steps are skipped (step 1, 2 and 3).

**Comment by DeNo64** [comment]
Human error. Used parentheses rather and curly brackets. Sorry mate. Thanks for pointing me the right direction.

My next issue is that the Tray doesn't seem to be working. In the logs I get "Tray icon is not supported". (logs attached)
"2024-10-09T12:42:06.437+08:00  WARN 30466 --- [JavaFX-Launcher] com.getpcpanel.util.TrayService          : Tray icon is not supported"

I've done some googling and can't see anything related to required packages to get JavaFX tray icon support on Arch Linux. 
Are you aware of what could be the issue/what I'm missing to get the Tray icon working?

Thanks heaps


And for posterity I also needed to install 'ttf-ms-fonts' to get the text to show.

**Comment by DeNo64** [comment]
All good, got Tray working on GNOME. So it's a Waybar issue.

Thanks for the assistance and building this

Have a great day, mate :)
