### ISSUE TITLE
Label Color Customization on PCPanel mini

### ISSUE THREAD

**Issue by Benzeel** [nvdweem/PCPanel#68]
In the latest snapshot versions I cant customize the label colours for the PCPanel mini.
I could've sworn you could do in 1.6, I may be wrong. 
(I had to redo all of my settings and customization for my pro and mini since I accidentally deleted my profile when I moved to the snapshot)
I wanted to know if you could or could _not_ customize the label colours on the mini in the first place. 
if you _could_ before the 1.7 snapshots, do you think that could be re-added? thanks!

**Comment by nvdweem** [comment]
I don't think that was changed recently. I don't have a mini to check myself and I don't see any label code for the mini (there are KnobConfigs, SliderConfigs and SliderLabelConfigs, that implies that only sliders have labels that can be colored). The part that sends the lighting config to the device also doesn't seem to write label colors to the mini.
I expect that it was never possible.

You could try the official software and see if that has it. It can be installed next to this version, If the official software doesn't do it then the device most probably doesn't support it.
