### ISSUE TITLE
Application Finder

### ISSUE THREAD

**Issue by battlecator** [nvdweem/PCPanel#8]
Application finder does not work, so processes must be added manually. Also, in windows 10 21H2 processes are case sensitive (Signal.exe will work, where signal.exe will not).

ps: add a public paypal : ) want to buy you a bear or coffee (really helped me out w/ your version of PCPanel)

**Comment by nvdweem** [comment]
The next snapshot build should make the processes case-insensitive. 

I installed a Windows 10 21H2 VM and the application seems to work as intended in both the 1.4 and 1.5-snapshot versions. I know there was an issue in the 1.3 version but that one is quite old already.
If you are using 1.4 or later, what does it not do for you? Are there errors in the log? (main pane, Settings cogwheel, Logs, Show log, logging.log file)

In this version of the application there are 3 types of 'application finders'.
1. Shortcut option: Here you can pick any executable
2. Kill process option: All running processes are shown
3. Volume options: Only processes that have a volume slider in the Windows Volume Mixer are shown here

Is it that you are getting the third one but you want to select an application that isn't running yet?


I also added donation info to the repository. Even though it would be appreciated, there really is no need to donate though, as long as I'm still using the PCPanel I'll try to keep the software working ;).

**Comment by battlecator** [comment]
Tbh, from the point that I added my desired programs manually and it works I 'm fine with that : )

version: 1.5-snapshot
dxdiag report: [DxDiag.txt](https://github.com/nvdweem/PCPanel/files/9331344/DxDiag.txt)

I open the application finder window, while discord is open in the background. For instance discord does not show up at all. Am I missing something though o.O ? 
![892-625-max](https://user-images.githubusercontent.com/36232657/184492778-1095e3ee-30de-426e-91cd-90fb91cc74bc.png)

![882-499-max](https://user-images.githubusercontent.com/36232657/184492771-8ecbd10c-9653-4782-825e-bbe7b0c959d5.png)

The requested logs files:
[logfile.0.txt](https://github.com/nvdweem/PCPanel/files/9331337/logfile.0.txt)
[logfile.1.txt](https://github.com/nvdweem/PCPanel/files/9331338/logfile.1.txt)
[logfile.txt](https://github.com/nvdweem/PCPanel/files/9331339/logfile.txt)

**Comment by nvdweem** [comment]
Discord is a bit strange in how it handles sounds (see #7). It also seems to only create a volume mixer when it has (recently) played a sound. Discord seems to register an uncontrollable mixer for some (to me) unknown reason, and a controllable one for volume:
![image](https://user-images.githubusercontent.com/830783/184493319-a0f9aa61-67dd-4f87-9aa3-beeabcaa5b55.png)

But in your screenshot I would have expected the browser and System sounds as well, so something strange is going on there. It should list the applications that are controllable, so if the volume changing works I would have not expected it to be empty.

The log files you attached are from the original software (from the `%localappdata%\PCPanel Software\logs` folder), the log files from my version should be in `%userprofile%\.pcpanel\logs`

Also, many thanks for the donation :)

**Comment by battlecator** [comment]
I installed windows on a VM with the same iso file I used for my current installation. It works on the VM just fine. I 'm might do a fresh install in the following weeks and get back to you. Looks like, I fucked up something on my end (as usual 😄).

![1922-1154-max](https://user-images.githubusercontent.com/36232657/184494189-c9f28cbc-8900-40f6-bb31-b80a893d9518.png)
